#!/usr/bin/env python

import sys
import re

import pyutil

if len(sys.argv) != 2:
  print 'usage: %s <logdir>' % sys.argv[0]
  exit(1)

logdir = sys.argv[1]

pyutil.read_machinelist(logdir)
maxmap = { }
phi_reg = re.compile('\\bPHI\\b')
logfile = open(logdir + '/scale.log')
for line in logfile:
  if phi_reg.search(line):
    entries = line.split()
    observed_ip = entries[9][1:]
    observer_ip = entries[11][1:]
    phi = float(entries[13])
    observed_nid = pyutil.ip2nid[observed_ip]
    observer_nid = pyutil.ip2nid[observer_ip]
    if not observed_nid in maxmap or maxmap[observed_nid][0] < phi:
      maxmap[observed_nid] = (phi, observer_nid)

for i in range(1, pyutil.num_node + 1):
  print i, pyutil.nid2ip[i], 'is seen as', maxmap[i][0], 'by', maxmap[i][1], pyutil.nid2ip[maxmap[i][1]]

