#!/usr/bin/env python

import sys, re
import pyutil

if len(sys.argv) < 2:
  print 'usage: receive_token <logdir> [monitored_node]'
  exit(1)


logdir = sys.argv[1]

pyutil.read_machinelist(logdir)
num_nodes = pyutil.num_node
if len(sys.argv) == 3:
  node_range = [int(sys.argv[2])]
else:
  node_range = range(1, num_nodes + 1)

remove_pattern = re.compile('.*; ')
data = []
for i in node_range:
  logfile = open(logdir + '/node' + str(i) + '/scale1.log')
  for logline in logfile:
    if 'newNodeToken' in logline or 'newVersionToken' in logline:
      entries = remove_pattern.sub('', logline).split()
      new_node_token = int(entries[1].split('=')[1])
      new_version_token = int(entries[4].split('=')[1])
      new_token = new_node_token + new_version_token
      if new_token:
        data.append(new_token)
data.sort()
datasize = len(data)
lqpos = datasize / 4
medpos = datasize / 2
uqpos = lqpos * 3
print 'datasize=%d min=%f lq=%f med=%f uq=%f max=%f' % \
    (datasize, data[0], data[lqpos], data[medpos], data[uqpos], data[-1])

