#!/usr/bin/env python

import sys
from datetime import *

import pyutil

if len(sys.argv) < 3:
  print 'usage: gossip_count <logdir> <observed_node> [time_period]'
  print 'example: gossip_count n 4'
  print 'example: gossip_count n 4 60'
  exit(1)
  
logdir = sys.argv[1]
observed_node = int(sys.argv[2])

if len(sys.argv) >= 4:
  time_period = int(sys.argv[3])
else:
  time_period = None

machinelist = open(logdir + '/machinelist')
pyutil.read_machinelist(logdir)
observed_node_ip = pyutil.nid2ip[observed_node]

gossiplist = []

for observer in pyutil.nid2ip:
  if observer == observed_node:
    continue
  logfile = open(logdir + '/node' + str(observer) + '/scale1.log')
  recline = 'receive info of /' + observed_node_ip + ' '
  rectimehist = []
  for logline in logfile:
    if recline in logline:
      entries = logline.split()
      time = (entries[2] + ' ' + entries[3]).split(',')[0]
      timestamp = datetime.strptime(time, '%Y-%m-%d %X')
      rectimehist.append(timestamp)
  if time_period:
    firsttime = rectimehist[0]
    time_period_list = []
    for rectime in rectimehist:
      if (rectime - firsttime).total_seconds() > time_period:
        break
      time_period_list.append(rectime)
  else:
    time_period_list = rectimehist[:]
  gossiplist.append(len(time_period_list))
gossiplist.sort()
datasize = len(gossiplist)
lqpos = datasize / 4
medpos = datasize / 2
uqpos = lqpos * 3
print 'datasize=%d min=%f lq=%f med=%f uq=%f max=%f' % \
    (datasize, gossiplist[0], gossiplist[lqpos], gossiplist[medpos], gossiplist[uqpos], gossiplist[-1])

