#!/usr/bin/env python

import sys
import re

import pyutil

if len(sys.argv) != 4:
  print 'usage: %s <logdir> <observer> <observed_node>' % sys.argv[0]
  exit(1)

logdir = sys.argv[1]
observer = int(sys.argv[2])
observed_node = int(sys.argv[3])

pyutil.read_machinelist(logdir)
maxphi = 0
phi_reg = re.compile('\\bPHI\\b')
logfile = open(logdir + '/node' + str(observer) + '/scale1.log')
for line in logfile:
  if phi_reg.search(line):
    entries = line.split()
    ip = entries[9][1:]
    phi = float(entries[11])
    nid = pyutil.ip2nid[ip]
    if nid == observed_node and maxphi < phi:
      maxphi = phi

print observed_node, pyutil.nid2ip[observed_node], 'is seen as', maxphi, 'by', observer, pyutil.nid2ip[observer]

