#!/usr/bin/env python

import sys

if len(sys.argv) != 3:
  print 'usage: node_exec_time <logdir> <monitored_node>'
  exit(1)

logdir = sys.argv[1]
monitored_node = sys.argv[2]
logfile = open(logdir + '/node' + monitored_node + '/scale1.log')
exetimehist = []
for line in logfile:
  if 'GOSSIP_DIGEST_ACK' in line:
    entries = line.split()
    exetime = int(entries[13])
    exetimehist.append(exetime)
exetimehist.sort()
datasize = len(exetimehist)
lqpos = datasize / 4
medpos = datasize / 2
uqpos = lqpos * 3
total = sum(exetimehist)
avg = total / datasize
print 'datasize=%d min=%f lq=%f med=%f uq=%f max=%f avg=%f sum=%f' % \
    (datasize, exetimehist[0], exetimehist[lqpos], exetimehist[medpos], 
    exetimehist[uqpos], exetimehist[-1], avg, total)

