#!/bin/sh

if [ $# -ne 1 ] ; then
  echo "usage: scalegraph <expdir>" 
  exit 1
fi

expdir=$1
output=$expdir/output2
mkdir -p $output

observer=32
observed_node=9
logdir=$expdir/n32
max_phi $logdir $observer $observed_node > $output/max_phi_32
phi_distribute $logdir $observer $observed_node > $output/phi_distribute_32
node_exec_time $logdir $observed_node > $output/node_exec_time_32
gossip_interval $logdir $observer $observed_node 60 > $output/gossip_interval_32
num_false_detected_node $logdir $observed_node > $output/num_false_detected_node_32

observer=64
observed_node=25
logdir=$expdir/n64
max_phi $logdir $observer $observed_node > $output/max_phi_64
phi_distribute $logdir $observer $observed_node > $output/phi_distribute_64
node_exec_time $logdir $observed_node > $output/node_exec_time_64
gossip_interval $logdir $observer $observed_node 60 > $output/gossip_interval_64
num_false_detected_node $logdir $observed_node > $output/num_false_detected_node_64

observer=128
observed_node=57
logdir=$expdir/n128
max_phi $logdir $observer $observed_node > $output/max_phi_128
phi_distribute $logdir $observer $observed_node > $output/phi_distribute_128
node_exec_time $logdir $observed_node > $output/node_exec_time_128
gossip_interval $logdir $observer $observed_node 60 > $output/gossip_interval_128
num_false_detected_node $logdir $observed_node > $output/num_false_detected_node_128
