#!/bin/sh

if [ $# -ne 2 ] ; then
  echo "usage: scalegraph.sh <expdir> <observed_node>" 
  exit 1
fi

expdir=$1
observed_node=$2
output=$expdir/output3
mkdir -p $output
for i in 32 64 128; do
  logdir=$expdir/n$i
  max_phi_distribute $logdir $observed_node > $output/max_phi_distribute_$i
  gossip_count_distribute $logdir $observed_node 60 > $output/gossip_count_distribute_$i
done
