#!/usr/bin/env python

import sys
from datetime import *

import pyutil

if len(sys.argv) != 2:
  print 'usage: time2stable <logdir>'
  exit(0)

logdir = sys.argv[1]

# column = 12 16 20 24
pyutil.read_machinelist(logdir)
num_nodes = pyutil.num_node
start = None
end = None
ll = ''
for i in range(1, num_nodes + 1):
  logfile = open(logdir + '/node' + str(i) + '/scale1.log')
  stable = False
  for logline in logfile:
    if 'RingInfo' in logline:
      ll = logline
      entries = logline.split()
      time = (entries[2] + ' ' + entries[3]).split(',')[0]
      timestamp = datetime.strptime(time, '%Y-%m-%d %X')
      if not start or start > timestamp:
        start = timestamp
        continue
      seen = int(entries[11][:-1])
      nonmember = int(entries[15][:-1])
      notcompleted = int(entries[19][:-1])
      dead = int(entries[23])
      if seen == num_nodes and not nonmember and not notcompleted and not dead:
        if not end or (end < timestamp and not stable):
          end = timestamp
          stable = True
      else:
        stable = False
  if not stable:
    #print '-1.0', i, ll
    print '-1.0'
    exit(0)
tts = (end - start).total_seconds()
print tts
