#!/bin/sh

operating_dir=`dirname $0`

conf_file=$operating_dir/sc.conf
if [ $# -eq 1 ]; then
  conf_file=$1
fi

if [ ! -f $conf_file ]; then
  echo There is no such configuration file : $conf_file
  exit 1
fi

. $conf_file

mkdir -p $operating_dir/pid

base_jvm_opts="-XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime -XX:+PrintGCApplicationConcurrentTime -Dcassandra.log.dir=$operating_dir/log"
if [ $property_file ]; then
  base_jvm_opts="$base_jvm_opts -Dbids.properties=$property_file"
fi
export CASSANDRA_HOME=$cassandra_home
#for jar in `ls $aspectj/lib/*.jar`; do
#  export CLASSPATH=$jar:$CLASSPATH
#done
i=1
mkdir $operating_dir/log
while [ $i -le $num_node ]; do
  if [ $id_offset ]; then
    id=`expr \( $id_offset - 1 \) \* $num_node + $i`
  else
    id=$i
  fi
  export CASSANDRA_CONF=$operating_dir/cassconf/conf$i
  export JVM_OPTS="$base_jvm_opts -Xloggc:$operating_dir/log/gc.${i} -Dlog4j.file.id=$i -Dcassandra.id=$id -Dcassandra.ring_delay_ms=5000 -Dnumnodes=$num_node"
  if [ $observed_nodes ]; then
    export JVM_OPTS="$JVM_OPTS -Dobserved.nodes=$observed_nodes"
  fi
  export NODE_ID=$i
  $operating_dir/bin/cassandra -p $operating_dir/pid/n${i}.pid
#  sleep `expr 5 + $i`
#  if [ $i -ne 1 ]; then
#    sleep 4
#  fi
  i=`expr $i + 1`
done
