#!/bin/sh

operating_dir=`dirname $0`

conf_file=$operating_dir/sc.conf
if [ $# -eq 2 ]; then
  conf_file=$1
  node_id=$2
elif [ $# -eq 1 ]; then
  node_id=$1
else
  echo Please specify node ID
  exit 1
fi

if [ ! -f $conf_file ]; then
  echo There is no such configuration file : $conf_file
  exit 1
fi

. $conf_file

base_jvm_opts="-Dcassandra.log.dir=$operating_dir/log"
if [ $property_file ]; then
  base_jvm_opts="$base_jvm_opts -Dbids.properties=$property_file"
fi
export CASSANDRA_HOME=$cassandra_home
for jar in `ls $aspectj/lib/*.jar`; do
  export CLASSPATH=$jar:$CLASSPATH
done
export CASSANDRA_CONF=$operating_dir/cassconf/conf$node_id
if [ $id_offset ]; then
  id=`expr \( $id_offset - 1 \) \* $num_node + $node_id`
elif
  id=$i
fi
export JVM_OPTS="$base_jvm_opts -Dcassandra.id=$id"
export NODE_ID=$node_id
mkdir -p $operating_dir/pid
bin/cassandra -p  $operating_dir/pid/node${node_id}.pid
