#!/usr/bin/env python

import sys
from datetime import *

import pyutil

#calculatingTime = datetime.strptime(timeStr, '%Y-%m-%d %X')

if len(sys.argv) != 2:
  print 'usage: total_downtime.py <logdir>'
  exit(0)

logdir = sys.argv[1]

pyutil.read_machinelist(logdir)
num_nodes = pyutil.num_node
total_downtime = 0.0
for i in range(1, num_nodes + 1):
  down_timestamp = {}
  logfile = open(logdir + '/node' + str(i) + '/node1.log')
  for logline in logfile:
    if 'now DOWN' in logline:
      entries = logline.split()
      time = (entries[2] + ' ' + entries[3]).split(',')[0]
      timestamp = datetime.strptime(time, '%Y-%m-%d %X')
      ip = entries[8]
      if ip in down_timestamp:
        print 'Detect down without up for', ip, 'by', i
      down_timestamp[ip] = timestamp
    elif 'now UP' in logline:
      entries = logline.split()
      ip = entries[8]
      if ip in down_timestamp:
        time = (entries[2] + ' ' + entries[3]).split(',')[0]
        timestamp = datetime.strptime(time, '%Y-%m-%d %X')
        downtime = (timestamp - down_timestamp[ip]).total_seconds()
        total_downtime += downtime
        del down_timestamp[ip]
  if down_timestamp:
    print i, down_timestamp
print total_downtime

