#!/usr/bin/env python

import sys
import re

import pyutil

if len(sys.argv) != 3:
  print 'usage: %s <logdir> <observed_node>' % sys.argv[0]
  exit(1)

logdir = sys.argv[1]
observed_node = int(sys.argv[2])

pyutil.read_machinelist(logdir)
phi_reg = re.compile('\\bPHI\\b')

maxphilist = []

for observer in pyutil.nid2ip:
  if observer == observed_node:
    continue
  maxphi = 0
  logfile = open(logdir + '/node' + str(observer) + '/node1.log')
  for line in logfile:
    if phi_reg.search(line):
      entries = line.split()
      ip = entries[10][1:]
      phi = float(entries[12])
      nid = pyutil.ip2nid[ip]
      if nid == observed_node and maxphi < phi:
        maxphi = phi
  maxphilist.append(maxphi)

maxphilist.sort()
datasize = len(maxphilist)
lqpos = datasize / 4
meanpos = datasize / 2
uqpos = lqpos * 3
print 'datasize=%d min=%f lq=%f mean=%f uq=%f max=%f' % \
    (datasize, maxphilist[0], maxphilist[lqpos], \
        maxphilist[meanpos], maxphilist[uqpos], maxphilist[-1])

