#!/bin/sh

if [ $# -ne 1 ]; then
  echo "usage: num_false_detect_node <logdir>"
  exit 1
fi
dir=$1
num_falsenode=0
for log in `ls $dir/node*/*.log`; do
  grep -q "now DOWN" $log
  if [ $? -eq 0 ]; then
    num_falsenode=`expr $num_falsenode + 1`
  fi
done 

echo $num_falsenode
