#!/usr/bin/env python

import sys
import pyutil

if len(sys.argv) != 4:
  print 'usage: phi_distribute.py <logdir> <observer> <observed_node>'
  print 'example: phi_distribute.py n 3 4'
  exit(1)
  
logdir = sys.argv[1]
observer = int(sys.argv[2])
observed_node = int(sys.argv[3])

pyutil.read_machinelist(logdir)
observer_ip = pyutil.nid2ip[observer]
observed_node_ip = pyutil.nid2ip[observed_node]

logfile = open(logdir + '/node' + str(observer) + '/node1.log')
philine = 'PHI for /' + observed_node_ip
phihist = []
for logline in logfile:
  if philine in logline:
    entries = logline.split()
    phihist.append(float(entries[12]))
phihist.sort()
datasize = len(phihist)
lqpos = datasize / 4
meanpos = datasize / 2
uqpos = lqpos * 3
print 'datasize=%d min=%f lq=%f mean=%f uq=%f max=%f' % \
    (datasize, phihist[0], phihist[lqpos], phihist[meanpos], phihist[uqpos], phihist[-1])

