#!/bin/sh

os=`uname`
if [ ! $os = Linux ]; then
  echo Multi-machine remote run supports only Linux
  exit 1
fi

cwd=`pwd`
scriptdir=`dirname $0`
cd $scriptdir
scriptdir=`pwd`
cd $cwd

. $scriptdir/readconfig

all_ip=`awk '{print $2}' $machinelist`

i=1

start_seed() {
  seed=$1
  shift
  ssh $seed "cd $operating_dir; ./allnode_start" &
  all_ip=$@
  i=`expr $i + 1`
  num_node=`expr $num_node - 1`
}

start_observers() {
  j=0
  while [ $j -lt $num_observers ]; do
    node=$1
    ssh $node "cd $operating_dir; ./allnode_start" &
    shift
    i=`expr $i + 1`
    j=`expr $j + 1`
    num_node=`expr $num_node - 1`
  done
  all_ip=$@
}

start_observed_nodes() {
  j=0
  while [ $j -lt $num_observed_nodes ]; do
    node=$1
    ssh $node "cd $operating_dir; ./allnode_start" &
    shift
    i=`expr $i + 1`
    j=`expr $j + 1`
    num_node=`expr $num_node - 1`
  done
  all_ip=$@
}

start_scalesim() {
  scalesim=$1
  ssh $scalesim "cd $operating_dir; ./scalesim_start" &
  i=`expr $i + 1`
  shift
  all_ip=$@
}

start_seed $all_ip
start_observers $all_ip
start_observed_nodes $all_ip
sleep 10
start_scalesim $all_ip

