#!/bin/sh

scriptdir=`dirname $0`
classpath=$scriptdir/../build/classes/main:$scriptdir/../build/classes/thrift:$scriptdir/../test/conf
for jar in ls $scriptdir/../lib/*.jar; do
  classpath=$classpath:$jar
done
for jar in ls $scriptdir/../build/lib/jars/*.jar; do
  classpath=$classpath:$jar
done

mode=normal
if [ ! -z $1 ] ; then
  mode=$1
fi

#end=128
#i=1
#rm -r /tmp/cassandra/*
#while [ $i -lt $end ]; do
#  java -Dfile.encoding=UTF-8 -classpath $classpath edu.uchicago.cs.ucare.cassandra.gms.RandomGossipProcessingMetric $mode $i 12
#  i=`expr $i + 1`
#done

max_curr_ver=255
max_new_ver=170
max_real_update=150

i=0
while [ $i -le $max_curr_ver ]; do
  j=0
  while [ $j -lt $max_new_ver ]; do
    k=0
    while [ $k -lt $max_real_update ]; do
      rm -r /tmp/cassandra/*
      java -Dfile.encoding=UTF-8 -classpath $classpath edu.uchicago.cs.ucare.cassandra.gms.RandomGossipProcessingMetric $mode $i $j $k 3
      k=`expr $k + 4`
    done
    j=`expr $j + 4`
  done
  i=`expr $i + 8`
done
