#!/bin/sh

os=`uname`
if [ ! $os = Linux ]; then
  echo Multi-machine IP setup script supports only Linux
  exit 1
fi

scriptdir=`dirname $0`

my_id=$1
shift
. $scriptdir/readconfig

num_machine=`wc -l $machinelist | awk '{print $1}'`
eval $(awk '{print "machine"$1"="$2}' $machinelist)

ip=192.168.${my_id}.1
ifconfig | grep -q "\<$ip\>"
if [ $? -ne 0 ]; then
  echo Adding $ip
  ifconfig eth0:$i $ip up
fi

i=1
while [ $i -le $num_machine ]; do
  if [ $i -eq $my_id ]; then
    i=`expr $i + 1`
    continue
  fi
  gw=$(eval echo \${machine$i})
  echo Adding route 192.168.${i}.0
  route add -net 192.168.${i}.0 netmask 255.255.255.0 gw $gw dev eth0
  i=`expr $i + 1`
done
