#!/bin/sh

scriptdir=`dirname $0`
. $scriptdir/readconfig
echo $num_node
classpath=$scriptdir/../build/classes/main:$scriptdir/../build/classes/thrift:$scriptdir/../test/conf
for jar in ls $scriptdir/../lib/*.jar; do
  classpath=$classpath:$jar
done
for jar in ls $scriptdir/../build/lib/jars/*.jar; do
  classpath=$classpath:$jar
done

JVM_OPTS="$JVM_OPTS -Dcassandra.unsafesystem=false"
JVM_OPTS="$JVM_OPTS -Dedu.uchicago.ucare.sck.recordEnabled=true"
JVM_OPTS="$JVM_OPTS -Dedu.uchicago.ucare.sck.replayEnabled=false"
JVM_OPTS="$JVM_OPTS -Dedu.uchicago.ucare.sck.failOnNotFound=true"
JVM_OPTS="$JVM_OPTS -Dedu.uchicago.ucare.sck.baseMessageFolder=/tmp/serialized_messages"
JVM_OPTS="$JVM_OPTS -Dedu.uchicago.ucare.sck.targetMemoizedMethod=handleMajorStateChange"

java $JVM_OPTS -Xmx16G -Xms16G -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintGCApplicationStoppedTime \
    -XX:+PrintGCApplicationConcurrentTime -Xloggc:/tmp/gc -classpath $classpath -Dobserved.nodes=$observed_nodes \
    edu.uchicago.cs.ucare.cassandra.gms.WholeClusterSimulator $num_node nome_boot.dat tok32 24 &
