#!/bin/sh

scriptdir=`dirname $0`
. $scriptdir/readconfig
classpath=$scriptdir/../build/classes/main:$scriptdir/../build/classes/thrift:$scriptdir/../test/conf
for jar in ls $scriptdir/../lib/*.jar; do
  classpath=$classpath:$jar
done
for jar in ls $scriptdir/../build/lib/jars/*.jar; do
  classpath=$classpath:$jar
done

java -classpath $classpath -Dobserved.nodes=$observed_nodes edu.uchicago.cs.ucare.cassandra.gms.WholeClusterSimulator $num_node nome_boot.dat nome_normal.dat &

