#!/bin/sh

script_dir=`dirname $0`

if [ -n "$JAVA_HOME" ]; then
  JAVA="$JAVA_HOME/bin/java"
else
  JAVA=java
fi 

if [ ! $CASSANDRA_HOME ]; then
    CASSANDRA_HOME=$script_dir/..
fi

cassandra_bin=$CASSANDRA_HOME/build/classes/main
CLASSPATH=$CLASSPATH:$CASSANDRA_CONF:$cassandra_bin

for jar in $CASSANDRA_HOME/lib/*.jar; do
    CLASSPATH=$CLASSPATH:$jar
done
if [ -z $CLASSPATH ]; then
  echo "You must set the CLASSPATH var" >&2
  exit 1
fi

if [ $# -eq 2 ]; then
  $JAVA -ea -cp $CLASSPATH -Xmx1024M com.netapp.atg.bids.tools.ExecutionTimeAnalyzer "$@"
elif [ $# -eq 1 ]; then
  setupfile=$1/rawdatalist
  outputdir=$1/output
  $JAVA -ea -cp $CLASSPATH -Xmx1024M com.netapp.atg.bids.tools.ExecutionTimeAnalyzer $setupfile $outputdir
fi
