#!/bin/sh

cwd=`pwd`
scriptdir=`dirname $0`
cd $scriptdir
scriptdir=`pwd`
cd $cwd

. $scriptdir/readconfig

rm -r $operating_dir/* 2> /dev/null

mkdir -p $operating_dir/cassconf
mkdir $operating_dir/log

i=1
while [ $i -le $num_node ]; do
  a=`expr \( $i - 1 \) / 255`
  b=`expr \( $i - 1 \) % 255 + 1`
  cp -r $scriptdir/resources/conf $operating_dir/cassconf/conf$i
  cd $operating_dir/cassconf/conf$i
  sed "s:\$operating_dir:$operating_dir:g" cassandra.yaml.template | sed "s:\$ip_address:127.0.${a}.${b}:g" | sed "s:\$id:$i:g" > cassandra.yaml
  cd $cwd
  i=`expr $i + 1`
done

if [ ! $cassandra_home ]; then
  cassandra_home=$scriptdir/..
fi

cp -r $scriptdir/resources/bin $operating_dir
cp $scriptdir/resources/allnode_start $operating_dir
cp $scriptdir/resources/onenode_start $operating_dir
cp $scriptdir/resources/onenode_stop $operating_dir
cp $scriptdir/resources/sc.properties $operating_dir

cp $scriptdir/nome_boot.dat $operating_dir/nome_boot.dat
cp $scriptdir/tok32 $operating_dir/nome_normal.dat

echo cassandra_home=$cassandra_home > $operating_dir/sc.conf
echo num_node=$num_node >> $operating_dir/sc.conf
echo aspectj=$aspectj >> $operating_dir/sc.conf
echo property_file=$property_file >> $operating_dir/sc.conf
echo observed_nodes=$observed_nodes >> $operating_dir/sc.conf

echo bids.outputdir=$rawdata_dir >> $operating_dir/sc.properties
mkdir $rawdata_dir
