#!/bin/sh

read_machinelist() {
  num_node=0
  while read line; do
    id=`echo $line | awk '{print $1}'`
    ip=`echo $line | awk '{print $2}'`
    eval "id_$id=$ip"
    dumb_ip=`echo $ip | sed 's/\./_/g'`
    eval "ip_$dumb_ip=$id"
    num_node=`expr $num_node + 1`
  done < $1
}

getip() {
  eval "echo \$id_$1"
}

getid() {
  dumb_ip=`echo $1 | sed 's/\./_/g'`
  eval "echo \$ip_$dumb_ip"
}

if [ "$logdir" -a ! "$hasread" ]; then
  read_machinelist $logdir/machinelist
  hasread=true
fi
