#!/usr/bin/env python

import sys

import pyutil

if len(sys.argv) != 2:
  print 'usage: exec_time.py <logdir>'
  exit(1)

logdir = sys.argv[1]

pyutil.read_machinelist(logdir)
num_mach = pyutil.num_mach
num_ins = pyutil.num_ins
ins_per_mach = pyutil.ins_per_mach

max_exe = 0
sum_exe = 0
for i in range(1, num_mach + 1):
  for j in range(1, ins_per_mach + 1):
    logfile = open('%s/node%d/scale%d.log' % (logdir, i, j))
    for line in logfile:
      if 'GOSSIP_DIGEST_ACK' in line:
        entries = line.split()
        exetime = int(entries[13])
        sum_exe += exetime
        if max_exe < exetime:
          max_exe = exetime

print 'avg=%d' % (sum_exe / num_ins)
#print 'avg=%d max=%d' % (sum_exe / num_ins, max_exe)

