#!/usr/bin/env python

import sys
import re

import pyutil

if len(sys.argv) != 2:
  print 'usage: %s <logdir>' % sys.argv[0]
  exit(1)

logdir = sys.argv[1]

pyutil.read_machinelist(logdir)
maxmap = { }
phi_reg = re.compile('\\bPHI\\b')
for i in range(1, pyutil.num_node + 1):
  logfile = open(logdir + '/node' + str(i) + '/node1.log')
  for line in logfile:
    if phi_reg.search(line):
      entries = line.split()
      ip = entries[10][1:]
      phi = float(entries[12])
      nid = pyutil.ip2nid[ip]
      if not nid in maxmap or maxmap[nid][0] < phi:
        maxmap[nid] = (phi, i)

for i in range(1, pyutil.num_node + 1):
  print i, pyutil.nid2ip[i], 'is seen as', maxmap[i][0], 'by', maxmap[i][1], pyutil.nid2ip[maxmap[i][1]]

