#!/bin/sh

if [ $# -ne 2 ]; then
  echo 'usage: wrong_false_detect.sh <logdir> <observed_node>'
  exit 1
fi

logdir=$1
observed=$2

scriptdir=`dirname $0`
. $scriptdir/util/shutil

observed_ip=`getip $observed`

num_false_detected_node=0
for log in `ls $logdir/node*/*.log`; do
  grep "now DOWN" $log | grep -q $observed_ip
  if [ $? -eq 0 ]; then
    num_false_detected_node=`expr $num_false_detected_node + 1`
  fi
done 

echo $num_false_detected_node

