#!/bin/sh

if [ $# -ne 1 ] ; then
  echo "usage: simscgraph <expdir>" 
  exit 1
fi

expdir=$1
output=$expdir/output
mkdir -p $output
for i in 32 64 128; do
  logdir=$expdir/n$i
  sim_maxphi $logdir > $output/max_phi_$i
  sim_gossip_interval $logdir 60 > $output/gossip_interval_$i
done
