#!/usr/bin/env python

import sys

import pyutil

if len(sys.argv) != 2:
  print 'usage: exec_time.py <logdir>'
  exit(1)

logdir = sys.argv[1]

pyutil.read_machinelist(logdir)
num_node = pyutil.num_node

max_exe = 0
sum_exe = 0
for i in range(1, num_node + 1):
  logfile = open(logdir + '/node' + str(i) + '/node1.log')
  for line in logfile:
    if 'GOSSIP_DIGEST_ACK' in line:
      entries = line.split()
      exetime = int(entries[14])
      sum_exe += exetime
      if max_exe < exetime:
        max_exe = exetime

print 'avg=%d max=%d' % (sum_exe / num_node, max_exe)

