#!/bin/sh

if [ $# -ne 3 ] ; then
  echo "usage: scalegraph.sh <expdir> <observer> <observed_node>" 
  exit 1
fi

expdir=$1
observer=$2
observed_node=$3
output=$expdir/output
mkdir -p $output
for i in 16 32 64 128; do
  logdir=$expdir/n$i
  all_max_phi $logdir > $output/all_max_phi_$i
  max_phi $logdir $observer $observed_node > $output/max_phi_$i
  phi_distribute $logdir $observer $observed_node > $output/phi_distribute_$i
  num_false_detect $logdir > $output/num_false_detect_$i
  num_false_detect_node $logdir > $output/num_false_detect_node_$i
  num_false_detected_node $logdir $observed_node > $output/num_false_detected_node_$i
  exec_time $logdir > $output/exec_time_$i
  node_exec_time $logdir $observed_node > $output/node_exec_time_$i
  time2stable $logdir > $output/time2stable_$i
  acc_downtime $logdir > $output/acc_downtime_$i
  gossip_interval $logdir $observer $observed_node > $output/gossip_interval_$i
done
