#!/bin/sh

operating_dir=`dirname $0`

conf_file=$operating_dir/sc.conf
if [ $# -eq 1 ]; then
  conf_file=$1
fi

if [ ! -f $conf_file ]; then
  echo There is no such configuration file : $conf_file
  exit 1
fi

. $conf_file

mkdir -p $operating_dir/pid

base_jvm_opts="-Dcassandra.log.dir=$operating_dir/log"

#export JVM_OPTS="$base_jvm_opts -Dlog4j.file.id=$i -Dcassandra.id=$id -Dcassandra.ring_delay_ms=5000"
export JVM_OPTS="$base_jvm_opts -Dlog4j.file.id=sc"
export CASSANDRA_HOME=$cassandra_home
export CASSANDRA_CONF=$operating_dir/cassconf/conf

bin/scalecass $num_node $id_offset $observers $observed_nodes 

